config/routes.rb
Rails.application.routes.draw do

  resources :articles
  resources :categories
  resources :guests
  resources :posts
  devise_for :users,
    controllers: {:registrations => "registrations"}
  resources :users

  root 'articles#index'

  get 'comments/create'
  get 'comments/destroy'

  resources :articles do
    resources :comments
    resources :likes
    resources :parts
  end
  
    resources :articles do
        member do
        #delete :delete_file
        delete :admin_delete_article
        get :return_to_article
        end
    end




  resources :posts do
    resources :answers
  end

  resources :answers do
    resources :answers
  end

  resources :users do
    member do
      delete :delete_avatar_attachment
    end
  end


  resources :posts do
    member do
      delete :admin_delete_post
    end
  end


  get 'pages/admin'
  get 'pages/about'

  resources :pages do
    member do
      post:confirm_guest_to_user
      post:refuse_guest
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/article.rb
class Article < ApplicationRecord

  require "mini_magick"

  belongs_to :user
  belongs_to :category

  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :parts, dependent: :destroy
  
  has_one_attached :header_image, dependent: :purge_later
  
  validates :header_image, presence: true


  def upcase_title
    title = self.title.upcase
  end

  def titleize_title
    title = self.title.titleize
  end

  def article_has_like?
    self.likes.count >= 1
  end

  def who_likes_article
    @likes = self.likes.to_a
    @liker = []
    @likes.each do |like|
      @liker << like.user.full_name
    end
    return @liker.join(", ")
  end


end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: %i[ show edit update destroy return_to_article admin_delete_article check_active_storage_blob_compatibility]
    before_action :downcase_fields, only: %i[ create update ]
    before_action :delete_empty_part, only: %i[ return_to_article update ]
    #after_action :check_active_storage_blob_compatibility, only: %i[ create update ]
    
    #after_action :define_first_img_as_cover_img, only: %i[ create ]
    #after_action :picture_format, only: %i[ create update ]
    

    # GET /articles 
    def index
        
    if params.has_key?(:category)
        @category = Category.find_by_name(params[:category])
        if Article.where(published: true).where(category: @category).count == 0
            @articles = Article.all.order("created_at DESC").where(published: true)
            flash.now[:notice] = "Aucune création dans la catégorie : #{params[:category]}. Voici l'ensemble des créations"
            params[:category] = nil
        else
            @articles = Article.where(published: true).where(category: @category).order("created_at DESC")
        end
        #@articles = Article.where(category: @category).order("created_at DESC")
    else
        @articles = Article.where(published: true).order("created_at DESC")
    end
    
    end

    # GET /articles/
    def show
        @article_parts = Part.where(article_id: @article.id).order("position ASC")
        @other_articles = Article.where(published: true).where(user_id: @article.user_id).where.not(id: @article.id)
        
        @comments = @article.comments.order("created_at ASC")
        @last_articles = Article.order("created_at DESC").first(2)
    end

    # GET /articles/new
    def new
        @article = Article.new
    end

    # GET /articles/1/edit
    def edit
    #@images = @article.images.order("created_at ASC")    
        @element= @article.parts.build
    end

    # POST /articles
    def create
      
      @article = Article.new(article_params)
      @head_img = @article.header_image

        if @article.save

          if !@head_img.content_type.start_with? 'image/'
            delete_attachment(@head_img)
            render :new
            #redirect_to edit_article_path(@article)
            flash[:alert] = "Le fichier joint comme image principale n'est pas une image" 
          else
            resize_attachement_img(@head_img)
            redirect_to edit_article_path(@article)
            #flash[:success] = "Votre publication a été correctement mise à jour" 
          end

        else
            render :new, status: :unprocessable_entity
            flash[:error] = "votre publication n'a pas été enregistrée"
        end

    end

    # PATCH/PUT /articles/1 or /articles/1.json
    def update

        @head_img = @article.header_image
        @article.update(article_params)

        if !@head_img.content_type.start_with? 'image/'
          delete_attachment(@head_img)
          redirect_to edit_article_path(@article)
          flash[:alert] = "Le fichier joint comme image principale n'est pas une image" 
        else
          resize_attachement_img(@head_img)
          redirect_to @article
          flash[:success] = "Votre publication a été correctement mise à jour" 
        end
    end

    # DELETE articles
    def destroy
        @article.destroy
        redirect_to user_path(current_user)
        flash[:success] = "L'article a été supprimé"
    end


    def return_to_article
        redirect_to @article
    end

    def admin_delete_article
        UserMailer.admin_delete_article_email(@article).deliver_now
        @article.destroy
        redirect_to articles_url
        flash[:alert] = "Cette publication a été supprimé. Un email a été envoyé à son créateur pour l'avertir"  
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_article
        @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:user_id, :title, :description, :category_id, :header_image)
    end

    def downcase_fields
      article_params[:title].downcase!
    end

    # If user cancel edit or confirm update, this method delete empty parts - paragrapph or image
    def delete_empty_part
      @article.parts.each do |part|
        if part.element_type === 'paragraph' && part.content.empty?
            part.destroy
        elsif part.element_type === 'image' && part.image.attached? == false
            part.destroy
        end
      end
    end

    def delete_attachment(blob)
      blob.purge   
    end


    def resize_attachement_img(img)
      image = MiniMagick::Image.open(img)
      image.resize "900x900"
      image.quality(80)
      delete_attachment(img)
      img.attach(io: File.open(image.path), filename: 'file.jpg')
    end
    
    # def delete_not_image_file(header_image)
    #     puts ' --------------------- inside delete ------------------'
    #     return unless !header_image.content_type.start_with? 'image/'
    #     @head_img.purge_later
    #     redirect_to edit_article_path(@article)
    #     flash[:alert] = "Le fichier joint comme image principale n'est pas une image" 
    #     puts ' --------------------- END  deleting------------------'
    # end

end

app/helpers/articles_helper.rb
module ArticlesHelper

  # return a centered crop landscape picture if picture is portrait
  def crop_portrait_post_picture(image)
    # return true if picture mode is portrait (heigth > width )
    width = image.blob.metadata[:width].to_i
    height = image.blob.metadata[:height].to_i
    if  width < height
      return image.variant(resize: "300x225^", gravity: "center", crop: "300x225+0+0")
    else 
      return image
    end   
  end

end

app/views/articles/_carousel.html.erb
<% if @article.images.count == 1 %>
    <%= image_tag @article.images.first, :width=>600, :crop=>"fill", class: "img-fluid" %>
<% elsif @article.images.attached? && @article.images.count > 1 %>
 <div id="myCarousel" class="carousel slide" data-bs-ride="carousel">

    <div class="carousel-indicators">
      <% @article.images.each_with_index do |image, index| %>
        <button type="button" data-bs-target="#myCarousel" data-bs-slide-to=<%= index %> class="<%= "active" if index.zero? %>" aria-current="true" aria-label="Slide 1"></button>
      <% end %>
    </div>

    <div class="carousel-inner">
      <% @article.images.each_with_index do |image, index| %>
        <div class="carousel-item <%= "active" if index.zero? %>">
          <img class="bd-placeholder-img" width="100%" height="100%" src="<%=  image_path(url_for(image)) %>"aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false">
          <!-- ORIGINAL CARROUSSEL WITH ALL THE INFO : LINKS OVER THE PICTURE - COULD BE A FEATURES 
          <div class="container">
            <div class="carousel-caption text-start">
              <h1>Example headline.</h1>
              <p>Some representative placeholder content for the first slide of the carousel.</p>
              <p><a class="btn btn-lg btn-primary" href="#">Sign up today</a></p>
            </div>
          </div>
          -->
        </div>
      <% end %>
    </div>
    
    <button class="carousel-control-prev" type="button" data-bs-target="#myCarousel" data-bs-slide="prev">
      <span><i class="fas fa-3x fa-arrow-circle-left"></i></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#myCarousel" data-bs-slide="next">
      <span><i class="fas fa-3x fa-arrow-circle-right"></i></span>
      <span class="visually-hidden">Next</span>
    </button>
    
  </div>
<% end %>

    

app/views/articles/_comments.html.erb
  <% @comments.each do |comment| %>
    <% unless !comment.persisted? %>
      <div class="comment">

        <div class="dark-plum">
            <small><%= comment.user.full_name %> : </small><span class="comment-body"><%= comment.body %></span>
        </div>
        
        <div class="d-flex justify-content-between comment-info">

          <div class="comment-space"><span class="">il y a <%= time_ago_in_words(comment.created_at) %></span></div>
          
          <% if comment.user.id == current_user.id%>
              <%= link_to [comment.article, comment], class: "hover", method: :delete, data: { confirm: 'Êtes vous sûr de vouloir supprimer votre commentaire ?' } do %>
                <span class=""><i class="fas fa-trash"></i></span>
              <% end %>
          <% end %>
        </div>
      </div>
    <% end %>
  <% end %>

app/views/articles/_reply_form.html.erb
<div class="card ml-5">
  <div class="card-body">
    <%= form_with(model: [@article, @comment]) do |f| %>
      <%= f.hidden_field :parent_id: :value => @article.id%>
      <div class="form-group">
        <%= f.label 'Reply' %>
        <%= f.text_area :body, class: 'form-control' %>
      </div>
      <%= f.submit 'Submit', class: 'btn btn-primary' %>
      <%= link_to 'Cancel', article_path(@article), class: 'btn btn-secondary' %>
    <% end %>
  </div>
</div>

app/views/articles/edit.html.erb
<div class="container main-wrapper edit-article">

    <h3 class='mb-5'>Mettre à jour mon article</h3>

    <div class="row">
<!-- LEFT COLUMN : Edite Article-->
        <div class="col-4">

            <%= button_to return_to_article_article_path(@article), class: "btn btn-secondary mb-3", method: :get, :title => "Retourner à l'article sans enregistrer les modifications" do %>
                <i class="fas fa-undo-alt"></i>  <span class=""> Annuler</span>
            <% end %>
            <div class="card">
                <div class="card-body">
                    <!-- Render editing article-->
                    <%= render 'form', article: @article %>
                </div>

                <div class="card-body">
                    <!-- Publish / Unpublih button -->
                    <% if @article.published? %>
                        <a href="#" 
                        class="btn btn-secondary col-12 mb-4"
                        data-reflex='click->PublisherReflex#unpublish'
                        data-article-id='<%= @article.id %>'
                        title="Masquer un article le rend invisble pour les autres utilisateurs, mais ne le supprime pas"><i class="fas fa-file-download"></i> Masquer
                        </a>
                    <% else %>
                        <a href="#" 
                        class="btn btn-primary col-12 mb-4"
                        data-reflex='click->PublisherReflex#publish'
                        data-article-id='<%= @article.id %>'
                        title="Publier un article le rend accessibles aux autres membres"><i class="fas fa-file-upload"></i> Publier
                        </a> 
                        <!-- 1 we call data-reflex - tell him what we want, whitch method AND what result #publish -->
                        <!-- data-post-id => use to provide extra info -->
                    <% end %>
                    <!-- Delete button-->
                    <%= button_to article_path(@article), class: "btn btn-danger col-12 mb-4", method: :delete, :title => 'Supprimer définitivement cet article et son contenu', data: { confirm: 'Êtes vous certain de vouloir supprimer cet article et son contenu ?' }  do %>
                        <i class="fas fa-trash"></i><span class=""> Supprimer cet article</span>
                    <% end %>

                </div>
            </div>
        </div>
<!-- RIGHT COLUMN : Edite Parts of the article-->
        <div class="col-8">
     
            <div class="d-flex justify-content-between">
            
                <div class="mb-3 d-flex">
                    <%= form_with(model: [@article, @element]) do |form| %>
                        <%= form.hidden_field :element_type, value: 'paragraph' %>
                        <%= button_tag(type: 'submit', class: 'element-btn btn btn-secondary mr-1', title: 'Ajouter un paragraphe') do %>
                            <i class="fas fa-paragraph"></i>
                        <% end %>
                    <% end %>
                    <%= form_with(model: [@article, @element]) do |form| %>
                        <%= form.hidden_field :element_type, value: 'image' %>
                        <%= button_tag(type: 'submit', class: 'btn btn-secondary', title: 'Ajouter une image') do %>
                            <i class="far fa-image"></i>
                        <% end %>
                    <% end %>
                </div> 
            
                <div class="text-end">
                    <% if @article.published? %>
                        <span class="badge bg-info">Publié il y a <%= time_ago_in_words(@article.published_at) %></span>
                    <% else %>
                        <span class="badge bg-secondary">Non Publié</span>
                    <% end %>
                </div>

            </div>



            <!-- @article.parts#edit -->
            <div class="card">
                <div class="card-body" data-controller="parts">
                    <ul id='parts-elements' data-action="drop->parts#sort">
                        <% @article.parts.order(position: :asc).each do |part| %>
                            <% if part.persisted? %>
                                <li data-id='<%= part.id %>' class="part-item">
                                    <% if part.paragraph? %> <!-- PARAGRAPH -->
                                        <div class="mb-4 p-3 paragraph">

                                            <div class="paragraph-content">
                                                <% if part.content.present? %>
                                                    <div class="text">
                                                        <%= part.content %>
                                                    </div>
                                                <% else %>
                                                    <div class="paragraph-content-empty">
                                                        <i class="far fa-edit"></i> Paragraphe vide, cliquer pour le modifier
                                                    </div>
                                                <% end %>
                                            </div>

                                            <div class="paragraph-form d-none">
                                                <%= form_with(model: [@article, part]) do |form| %>
                                                    <%= form.rich_text_area :content %>
                                                    <div class="mt-3 d-flex justify-content-between">
                                                        <div>
                                                            <%= form.submit "Enregistrer", class: 'btn btn-primary', title: 'enregistrer les modifications' %>
                                                            <a href="#" class="cancel btn btn-secondary" title="Ne pas enregistrer les modifications'">Annuler</a>
                                                        </div>
                                                        <%= link_to 'Supprimer', article_part_path(@article, part), method: :delete, class: 'btn btn-danger', data: { confirm: 'Êtes vous certain de vouloir supprimer ce paragraphe ?'}, title: 'Supprimer le paragraphe'%>
                                                    </div>
                                                <% end %>
                                            </div>

                                        </div>

                                    <% elsif part.image? %> <!-- IMAGE -->
                                        <div class="image mb-4 p-3">
                                            <% if part.image.present? %>
                                                <%= link_to article_part_path(@article, part), method: :delete, class: 'delete-img-btn btn btn-secondary mt-2', data: { confirm: 'Êtes vous certain de vouloir supprimer cette image?'}, title: "Supprimer l'image" do %>
                                                    <i class="fas fa-times"></i>
                                                <% end %>
                                                <%= image_tag(part.image) %>
                                            <% else %>
                                                <%= form_with(model: [@article, part]) do |form| %>
                                                    <%= form.file_field :image %>
                                                    <div class="mt-3"> 
                                                        <%= form.submit "Sauvegarder", class: 'btn btn-primary' %>
                                                        <a href="#" class="cancel btn btn-secondary">Annuler</a>
                                                    </div>
                                                <% end %>
                                            <% end %>
                                        </div>
                                    <% end %>
                                </li>
                            <% end %>
                        <% end %>
                    </ul>
                </div>
            </div>
        </div>
    </div>


</div>

app/views/articles/index.html.erb
<div class="container main-wrapper">

  <h1>Créations</h1>

  <hr>

  <% if params[:category] == nil %>
    <%= link_to 'Tout', articles_path, class: "filter-article-active" %>
  <% else %>
    <%= link_to 'Tout', articles_path, class: "filter-article" %>
  <% end %>

  <% Category.all.order("name ASC").each do |cat| %>
    <% if params[:category] == cat.name %>
      <%= link_to cat.name.capitalize, articles_path(category: cat.name), class: "filter-article-active" %>
    <% else %>
      <%= link_to cat.name.capitalize, articles_path(category: cat.name), class: "filter-article" %>
    <% end %>
  <% end %>

  <hr>

  <div class="row">
    <% @articles.each do |article| %>
    
    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4 col-xl-3">

      <%= link_to article do %>

        <div class="card">

          <div class="card-content">

            <!-- header_image -->
            <% if article.header_image.attached? %>
              <div class="card-img-top">
                <%= image_tag article.header_image, class: "img-fluid mx-auto d-block" %>
<!-- PENSER A CROPPING METHOD crop_portrait_post_picture -->
              </div>
            <% end %> 

            <div class="card-body">
              <h5 class="card-title"><%= article.title.capitalize %></h5>
              <div class="article-user">
                <%= article.user.full_name %>
              </div>
              <!-- -->
              <div class="card-text">
                <div class="mb-2">
                  publié le <%= l(article.published_at, format: :date) %>
                </div>
                <div>
                  <span class="article-badge-full"><%= article.category.name %></span>
                  <% if article.likes.count > 0 %>
                    <span class="social-badge"><i class="fas fa-heart info-icon"></i>   <%= article.likes.count %></span>
                  <% end %>
                  <% if article.comments.count > 0 %>
                    <span><i class="fas fa-comment-alt  info-icon"></i>   <%= article.comments.count %></span>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <% end %>
  </div>
</div>

app/views/articles/new.html.erb
<div class="container main-wrapper">
  <h1>Nouvelle Création</h1>

  <%= render 'form', article: @article %>

  <div class="d-flex flex-row-reverse">
    <div class="actions mt-2">
      <%= link_to 'Annuler', articles_path, class: 'btn btn-secondary' %>
    </div>
  </div>
  
</div>

app/views/articles/new.js.erb
document.querySelector("#reply-form-<%= @comment.parent_id %>").innerHTML = ("<%= j render 'reply_form', comment: @comment %>")

app/views/articles/show.html.erb
<div class="container main-wrapper">

  <!-- ARTICLE -->

  <header>
    <!-- TITLE - PUBLISHED - CATEGORY - LIKES - COMMENTS -->
    <div class="mb-4">
      <h1 class='mb-4'><%= @article.upcase_title %></h1>

      <div class="text d-flex justify-content-start">
        <% if user_signed_in? && current_user.id == @article.user.id %>
            <% if @article.published? %> 
                <span class="badge bg-info">Publié</span>
            <% else %>
                <span class="badge bg-secondary">Non Publié</span>
            <% end %>
        <% end %>


        <div class="article-badge-full"><%= @article.category.name %></div>

        <% if user_signed_in? %>
          <% if @article.comments.count > 0 %>
            <div class="article-data">
              <span><i class="fas fa-comment-alt info-icon"></i>  <%= @article.comments.count %></span>
            </div>
          <% end %>
          <% if @article.article_has_like? %>
            <div class="article-data">
              <span data-bs-toggle="tooltip" data-bs-placement="right" title="<%= @article.who_likes_article %>"><i class="fas fa-heart info-icon"></i>  <%= @article.likes.count %></span>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>

    <!-- Main Header -->
    <div class="row">

      <!-- Left Header : image -->
      <% if @article.header_image.present? %>
        <div class="col-5"><%=
           image_tag @article.header_image, class: "header-img" %>
        </div>
      <% end %>

      <!-- Right Header : content -->
      <div class="col-7">
        <div class="d-flex align-items-start flex-column" style="height:100%">
          <!-- User and Description -->
          <div>
            <!-- user -->
                <%= link_to @article.user do %>
                    <div class="d-flex justify-content-start mb-4">
                        <% if @article.user.avatar.attached? %>
                            <div class="post-avatar">
                                <%= image_tag @article.user.avatar.variant(resize_to_limit: [60, 60]), class: "rounded-circle" %>
                            </div>
                        <% end %>

                        <div class="align-self-center">
                            <h3 class="text"><strong><%= @article.user.full_name %></strong></h3>   
                        </div>
                    </div>
                <% end %>

            
            <!-- Published info -->   
            <% if @article.published? %>
                <div class="text article-data p-2">
                        publié le <%= l(@article.published_at, format: :date) %>
                </div>
            <% end %>
          
            <!-- description -->
            <div class="p-2">
              <div class="row">
                <div class='col-11'>
                  <h3>Description</h3>
                  <div class="text">
                    <%= @article.description %>
                  </div>
                </div>
              </div>
            </div>
          </div>

       
          

          <!-- Action Zone -->
            <div class="mt-auto p-2" id="post-index-title-wrapper">
                <div class="d-flex justify-content-start">
                    <% if user_signed_in? %>

                        <%= button_to article_likes_path(@article), :title => 'liker', class: "btn btn-primary social-badge", method: :post do %>
                            <i class="far fa-heart action-icon"></i>
                        <% end %>

                        <% if current_user.id != @article.user.id %>

                            <%= button_to user_path(@article.user_id), :title => 'profil', class: "btn btn-primary social-badge", method: :get do %>
                                <i class="far fa-user action-icon"></i>
                            <% end %>
                        <% end %>

                        <% if current_user.id == @article.user.id %>

                            <%= button_to edit_article_path(@article), :title => 'modifier ma publication', class: "btn btn-primary social-badge", method: :get do %>
                                <i class="far fa-edit action-icon"></i>
                            <% end %>

                            <%
=begin%>
 <%= button_to @article, class: "btn btn-danger social-badge", :title => 'supprimer ma publication', method: :delete, data: { confirm: 'Êtes vous certain de vouloir supprimer cet article ?' } do %>
                                <i class="far fa-trash-alt action-icon"></i>
                            <% end %> 
<%
=end%>

                        <% end %>

                    <% end %>
                </div>
            </div>

        </div>
      </div>
    </div>
  </header>

  <!-- ARTICLE CONTENT & COMMENT -->
  <article>
    <div class="row">
      <!-- ARTICLE CONTENT -->
      <% if @article_parts.count > 0 %>

        <div class="col-8">
            <% @article_parts.each do |part| %>
            <div class="mb-4">
                <% if part.element_type === 'paragraph' && part.content.present?%>
                    <div class="p-3 text">
                        <%= part.content %>
                    </div>
                <% elsif part.element_type === 'image' && part.image.attached? %>
                        <%= image_tag part.image, class: 'article-img' %>
                <% end %>
            </div>
            <% end %>
        </div>

        <!-- COLUMN DE SEPARATION -->
        <div class="col-1"></div>
        
      <% end %>
      
      <!-- COMMENT -->
      <div class="col-3">

        <% if user_signed_in? %>
          <article>
            <div class="p-3">
                <h3><%= (@article.comments.count) < 2 ? 'Commentaire' : 'Commentaires'%></h3>
            </div>

            <!-- NEW COMMENT -->
            <div class="mb-5">
                <%= form_with(model: [@article, @article.comments.build]) do |f| %>
                    <%= f.hidden_field :user_id, value: current_user.id %>
                    <div class="form-group col-12 mb-2">
                        <div class="mb-2">
                            <%= f.text_area :body, class: 'form-control', required: true %></a>
                        </div>
                        <div class="d-flex justify-content-end">
                            <%= button_tag type: 'submit', class: "btn btn-outline-primary" do %>
                                <i class="far fa-comment-alt"></i>  <span>commenter</span></i>
                            <% end %>
                        </div>
                    </div>
                <% end %>
            </div>

            <!-- DISPLAY COMMENT -->
            <%= render 'comments' %>

          </article>
        <% end %>

      </div>
    </div>
  </article>



  <!-- ADMIN SECTION -->

  <% if user_signed_in? && current_user_is_admin? && current_user.id != @article.user.id %>
    <article>
      <div class="card-admin">
        <div class="d-flex justify-content-center">
          <div class="admin-content">
            <h3 class="dark-color d-none d-sm-none d-md-none d-lg-inline d-xl-inline">Section administrateur</h3>
          </div>
          <div class="admin-content">
            <%= link_to 'Supprimer cette publication', admin_delete_article_article_url(@article), class:"btn btn-outline-danger", method: :delete, data: { confirm: "Êtes vous certain de vouloir supprimer cette publication. Un email sera envoyé au membre afin de l'avertir de cette suppression" } %> 
          </div>
        </div>
        <div class="d-flex justify-content-center">
          <p class="dark-color d-none d-sm-none d-md-none d-lg-inline d-xl-inline">
            En tant qu'administrateur vous pouvez supprimer une publication si vous jugez son contenu inapropriété. <i class="fas fa-exclamation-triangle"></i> Cette action est irréversible !
          </p>
        </div>
      </div>
    </article>
  <% end %>

  <!-- OTHER USER ARTICLE -->

  <% if @other_articles.count > 0 %>

  <hr>

    <article>
      <h3 class='mb-4'><%= (@other_articles.count) > 2 ? 'Autres créations' : 'Autre création'%> de <%= @article.user.first_name.capitalize%></h3>

      <div class="row">
        <% @other_articles.each do |article| %>
          <div class="col-6 col-sm-6 col-md-4 col-lg-3 col-xl-3">
              <%= link_to (article) do %>
                <div class="card-small">
                  <% if article.header_image.attached? %>
                    <div class="card-img-top mb-1">
                      <%= image_tag (article.header_image), class: "img-fluid" %> 
                    </div>
                  <% end %>
                  <div class="card-body">
                    <h5><%= article.title.capitalize %></h5>
                    <div class="card-text">
                      <div class="mb-2">
                        publié le <%= l(article.created_at, format: :date) %>
                      </div>
                      <div>
                        <span class="article-badge-full"><%= article.category.name %></span>
                        <% if article.comments.count > 0 %>
                          <span><i class="fas fa-comment-alt info-icon"></i>  <%= article.comments.count %></span>
                        <% end %>
                        <% if article.likes.count > 0 %>
                          <span class="social-badge"><i class="fas fa-heart info-icon"></i>  <%= article.likes.count %></span>
                        <% end %>
                      </div>
                    </div>
                  </div>
                </div>
              <% end %>
            </div>
        <% end %>
      </div>
    </article>
  <% end %>

</div><!-- END OF CONTAINER -->








 