config/routes.rb
Rails.application.routes.draw do

  resources :articles
  resources :categories
  resources :guests
  resources :posts
  devise_for :users,
    controllers: {:registrations => "registrations"}
  resources :users

  root 'articles#index'

  get 'comments/create'
  get 'comments/destroy'

  resources :articles do
    resources :comments
    resources :likes
    resources :parts
  end
  
    resources :articles do
        member do
        #delete :delete_file
        delete :admin_delete_article
        get :return_to_article
        end
    end




  resources :posts do
    resources :answers
  end

  resources :answers do
    resources :answers
  end

  resources :users do
    member do
      delete :delete_avatar_attachment
    end
  end


  resources :posts do
    member do
      delete :admin_delete_post
    end
  end


  get 'pages/admin'
  get 'pages/about'

  resources :pages do
    member do
      post:confirm_guest_to_user
      post:refuse_guest
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :column

  has_one_attached :picture, dependent: :purge_later

  has_many :answers, as: :answerable, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true



  def display_created_at
    create = created_at.strftime("%d %B %Y")
  end

  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy admin_delete_post ]
  after_action :picture_format, only: %i[ create update ]

  # GET /posts or /posts.json
  def index
    


    if params.has_key?(:column)
      @column = Column.find_by_name(params[:column])
      if Post.where(column: @column).count == 0
        @posts = Post.all.order("created_at DESC")
        flash.now[:notice] = "Aucune annonce dans la catégorie : #{params[:column]}. Voici l'ensemble des annonces"
        params[:column] = nil
      else
        @posts = Post.where(column: @column).order("created_at DESC")
      end
      #@articles = Article.where(category: @category).order("created_at DESC")
    else
      @posts = Post.all.order("created_at DESC")
    end

  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post }
        flash[:success] = "Votre annonce est bien enregistrée"
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post }
        flash[:success] = "Votre annonce a correctement été modifiée"
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      flash[:success] = "votre annonce a bien été supprimée" 
      
      format.json { head :no_content }
    end
  end

  def admin_delete_post
    UserMailer.admin_delete_post_email(@post).deliver_now
    @post.destroy
    redirect_to posts_url
    flash[:alert] = "Cette annonce a été supprimé. Un email a été envoyé à son créateur pour l'en avertir"     
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body, :user_id, :column_id, :picture)
    end


  # check if blob is an image, if not delete the blob and send a message 
  # then if the image isn't a variable? it convert to jpeg
  def picture_format
    return unless @post.picture.attached?
    if ! @post.picture.content_type.start_with? 'image/'
      @post.picture.purge
      flash[:error] = "Aucune image n'a été enregistré car le fichier joint n'est pas une image"  
    elsif ! image_blob_is_variable?(@post.picture)
      new_image = MiniMagick::Image.open(@post.picture)
      new_image.format "jpeg"
      @post.picture.attach(io: File.open(new_image.path), filename: @post.picture.filename.to_s, content_type: "image/jpg")
    end
  end


  # if image blob isn't representable convert in appropriate format
  # avoid to get HEIC for e.g. - impossible to get a variant on content_type not true
  def image_blob_is_variable?(image)
    image.variable?
  end

end

app/helpers/posts_helper.rb
module PostsHelper

  # return a centered crop landscape picture if picture is portrait
  def crop_portrait_post_picture(image)
    # return true if picture mode is portrait (heigth > width )
    width = image.blob.metadata[:width].to_i
    height = image.blob.metadata[:height].to_i
    if  width < height
      return image.variant(resize: "300x225^", gravity: "center", crop: "300x225+0+0")
    else 
      return image
    end   
  end

end

app/views/posts/_form.html.erb
<%= simple_form_for(@post) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">

    <div class="field mb-2">
      <% if current_user_is_admin? %>
        <%= f.select(:column_id, options_for_select(Column.order(name: :asc).pluck(:name, :id)), {:prompt => 'Choississez la rubrique de votre annonce :'}, { :class => 'form-control text', :style => '', required: true }) %>
      <% else %>
        <%= f.select(:column_id, options_for_select(Column.where.not(name: "annonce club").order("name ASC").map { |c| [c.name, c.id]}), {:prompt => 'Choississez la rubrique de votre annonce :'}, { :class => 'form-control text', :style => '', required: true, }) %>
      <% end %>
    </div>

    <%= f.hidden_field :user_id, :value => current_user.id %>
    <%= f.input :title, required: true, label: 'Titre de votre annonce', :input_html => { :class => 'text' } %>
    <%= f.input :body, required: true, label: 'Texte de votre annonce',:input_html => {:rows => 7} %>
    <%= f.label :picture %>
    <%= f.file_field :picture, direct_upload: true, label: 'Vous pouvez ajouter une photo à votre annonce', class: "form-control" %>
  </div>

  <div class="form-actions mt-2">
    <%= f.button :submit, 'Poster mon annonce', class: "btn btn-primary mb-2" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class="container main-wrapper">
  <h1>Modifier mon annonce</h1>

  <%= render 'form', post: @post %>

  <%= link_to 'Annuler', @post,  class: 'btn btn-secondary' %>
  
</div>

app/views/posts/index.html.erb
<div class="container main-wrapper">

  <div>
    <h1>Annonces</h1>
  </div>

  <!-- ACTION ZONE -->
  <hr>

  <div class="d-flex justify-content-between">
    <div id="d-flex align-items-center flex-wrap">
      <% if params[:column] == nil %>
        <div id="post-filter-wrapper">
          <%= link_to 'Tout', posts_path, class: "filter-post-active" %>
        </div>
      <% else %>
        <div id="post-filter-wrapper">
          <%= link_to 'Tout', posts_path, class: "filter-post" %>
        </div>
      <% end %>

      <% Column.all.each do |rubrique| %>
        <% if params[:column] == rubrique.name %>
          <div id="post-filter-wrapper">
            <%= link_to rubrique.name.capitalize, posts_path(column: rubrique.name), class: "filter-post-active" %>
          </div>
        <% else %>
          <div id="post-filter-wrapper">
            <%= link_to rubrique.name.capitalize, posts_path(column: rubrique.name), class: "filter-post" %>
          </div>
        <% end %>
      <% end %>
    </div>
    
    <% if user_signed_in? %>
      <div class="align-self-center">
        <%= button_to new_post_path, :title => 'nouvelle annonce', class: "btn btn-secondary", method: :get do %>
          <i class="fas fa-bullhorn"></i>
        <% end %>
      </div>
    <% end %>
  </div>

  <hr>

  <!-- POST -->

  <% if @posts.count != 0 %>
    <div class="row">
        <% @posts.each do |post| %>
            <div class="col-12">
                <div class="post-card">
                <%= link_to (post) do %>
                    <div class="row">
                    <!-- img -->
                    <% if post.picture.attached? %>
                        <div class="col-3 col-sm-4 col-md-4 col-lg-3 col-xl-3">
                        <%= image_tag crop_portrait_post_picture(post.picture), class: "img-fluid" %>
                        </div>
                    <% end %>
                    <!-- info text -->
                    <% if post.picture.attached? %>
                        <div class="col-9 col-sm-8 col-md-8 col-lg-9 col-xl-9 d-flex align-items-start flex-column">
                    <% else %>
                        <div class="col-12 d-flex align-items-start flex-column">
                    <% end %>
                        <!-- title -->
                        <div id="post-index-title-wrapper">
                        <div class="d-flex justify-content-between">
                            <div class="mr-auto">
                            <h2><%= post.title %></h2>
                            </div>
                            <div class="ml-auto">
                            <span class="article-info post-badge-full"><%= post.column.name %></span>
                            </div>
                        </div>
                        </div>

                        <!-- description -->
                        <div class="d-none d-sm-none d-md-none d-lg-inline d-xl-inline">
                        <div class="post-body-index">
                            <%= post.body %>
                        </div>
                        </div>

                        <!-- avatar user info -->
                        <div class="mt-auto">
                        <div class="d-flex flex-row">
                            <div>
                            <% if post.user.avatar.attached? %>
                                <div class="post-index-avatar">
                                <%= image_tag post.user.avatar.variant(resize_to_limit: [40, 40]), class: "rounded-circle" %>
                                </div>
                            <% end %>
                            </div>
                            <div class="post-publish-info">
                                <strong><%= post.user.full_name %></strong>
                            <div>
                                <span class="post-publish">posté il y a <%= time_ago_in_words(post.created_at) %></span>
                                <% if post.answers.count > 0 %>
                                <span class="post-badge"><i class="dark-plum fas fa-comment-alt info-icon"></i>  <%= post.answers.count %></span>
                                <% end %>
                            </div>
                            </div>
                        </div>
                        </div>
                    </div>
                    </div>
                <% end %>
                </div>
            </div>
        <% end %>
    </div>
  <% else %>
    <p>Aucune annonce est publiée à ce jour</p>
  <% end %>

</div>

app/views/posts/new.html.erb
<div class="container  main-wrapper">
  <h1>Nouvelle annonce</h1>

  <%= render 'form', post: @post %>

  <%= link_to 'Annuler', @post,  class: 'btn btn-secondary' %>
</div>

app/views/posts/show.html.erb
<div class="container main-wrapper">

    <header>
        <h1><%= @post.title %></h1>
        <div class="d-flex justify-content-start">
            <span class="badge bg-secondary"><%= @post.column.name %></span><span class="text muted"><small>posté il y a <%= time_ago_in_words(@post.created_at) %></small></span>
        </div>
    </header>

    <article>
        <div class="row">
            <!-- left image -->
            <% if @post.user.avatar.attached? %>
                <div class="col-4">
                    <%= image_tag @post.picture, class: "article-img" %>
                </div>
            <% end %>

            <!-- right content -->
            <% if @post.user.avatar.attached? %>
                <div class="col-8">
            <% else %>
                <div class="col-12">
            <% end %>

                <div class="d-flex align-items-start flex-column" style="height:100%">

                    <%= link_to @post.user do %>
                        <div class="d-flex justify-content-start mb-4">
                            <% if @post.user.avatar.attached? %>
                                <div class="post-avatar">
                                    <%= image_tag @post.user.avatar.variant(resize_to_limit: [60, 60]), class: "rounded-circle" %>
                                </div>
                            <% end %>

                            <div class="align-self-center">
                                <h3 class="text">annonce de <strong><%= @post.user.full_name %></strong></h3>
                                <!--<span class="text muted"><small>posté il y a <%= time_ago_in_words(@post.created_at) %></small></span>-->
                            </div>
                        </div>
                    <% end %>

                    <div class="post-text">
                        <%= @post.body %>
                    </div>
                    <!-- ACTION ZONE -->
                    <div class="mt-auto" id="post-index-title-wrapper">
                        <div class="d-flex justify-content-start p-3">

                            <% if user_signed_in? %>
                                    <div class="article-action d-flex justify-content-around">

                                    <% if current_user.id == @post.user.id %>
                                        <%= button_to edit_post_path(@post), :title => 'modifier mon annonce', class: "btn btn-secondary social-badge", method: :get do %>
                                            <i class="far fa-edit action-icon"></i>
                                        <% end %>

                                        <%= button_to @post, class: "btn btn-danger social-badge", :title => 'supprimer mon annonce', method: :delete, data: { confirm: 'Êtes vous certain de vouloir supprimer cette annonce ?' } do %>
                                            <i class="far fa-trash-alt action-icon"></i></span>
                                        <% end %>
                                    <% end %>

                                    <% if current_user.id != @post.user.id %>
                                        <%= button_to user_path(@post.user_id), :title => 'profil', class: "btn btn-secondary social-badge", method: :get do %>
                                            <i class="far fa-user action-icon"></i>
                                        <% end %>
                                    <% end %>

                                    <%= link_to posts_path, class: "btn btn-secondary social-badge", :title => 'retour aux annonces', method: :get do %>
                                        <i class="far fa-caret-square-left action-icon" alt="Accueil"></i>
                                    <% end %>

                                    </div>
                            <% end %>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </article>

    <hr class="m-4">


<!-- ANSWER SECTION : see answers-->
  <% if user_signed_in? %>
      <!-- ANSWER SECTION : post answer -->
    <article  class="p-4">
        <div class="mb-4">
          <%= form_with(model: [@post, Answer.new]) do |f| %>
              <%= f.hidden_field :user_id, value: current_user.id %>
            <div class="form-group col-9 mb-2">
              <%= f.text_area :body, class: 'form-control', placeholder: "répondre à l'annonce de #{@post.user.first_name.capitalize}", required: true %>
            </div>
            <div class="col-9 d-flex justify-content-end">
                <%= button_tag type: 'submit', class: "btn btn-outline-secondary" do %>
                <i class="far fa-comment-alt"></i>  <span>répondre</span></i>
                <% end %>
            </div>
          <% end %>
        </div>

      <% if @post.answers.count > 0 %>
        <h3><%= (@post.answers.count) < 2 ? 'Réponse' : 'Réponses'%></h3>
        <ul>
          <%= render @post.answers %>
        </ul>
      <% end %>
    </article>
  <% end %>

<!-- ADMIN SECTION -->

  <% if current_user_is_admin? && current_user.id != @post.user.id %>
    <article>
      <div class="card-admin">
        <div class="d-flex justify-content-center">
          <div class="admin-content">
            <h3 class="dark-color d-none d-sm-none d-md-none d-lg-inline d-xl-inline">Section administrateur</h3>
          </div>
          <div class="admin-content">
            <%= link_to 'Supprimer cette annonce', admin_delete_post_post_url(@post), class:"btn btn-outline-danger", method: :delete, data: { confirm: "Êtes vous certain de vouloir supprimer cette annonce. Un email sera envoyé au membre afin de l'avertir de cette suppression" } %> 
          </div>
        </div>
        <div class="d-flex justify-content-center">
          <p class="dark-color d-none d-sm-none d-md-none d-lg-inline d-xl-inline">
            En tant qu'administrateur vous pouvez supprimer une publication si vous jugez son contenu inapropriété. <i class="fas fa-exclamation-triangle"></i> Cette action est irréversible !
          </p>
        </div>
      </div>
    </article>
  <% end %>
  
  
</div>